app1: 
  image: alizarion/openidc-php-demo
  ports:
   - "81:80"
app2: 
  image: alizarion/openidc-java-demo
  ports:
   - "82:8080"
keycloak-db: 
  image: alizarion/keycloak-mysql-db
keycloak-app: 
  image: jboss/keycloak-mysql
  links:
    - keycloak-db
openidc-proxy:
  image: alizarion/openidc-proxy
  environment:
  - OIDCProviderMetadataURL=${OIDCProviderMetadataURL}/.well-known/openid-configuration
  - OIDCClientID=${OIDCClientID}
  - OIDCClientSecret=${OIDCClientSecret}
  - OIDCRedirectURI=http://localhost/app1/redirect_uri
  - http_proxy=${http_proxy}
  - https_proxy=${https_proxy}
  - no_proxy=${no_proxy}
  ports:
   - "80:80"
  links:
   - app1
   - app2

   
