app1: 
  image: alizarion/openidc-php-demo
  ports:
   - "81:80"
app2: 
  image: alizarion/openidc-java-demo
  ports:
   - "82:8080"
keycloak-db: 
  image: alizarion/keycloak-mysql-db
keycloak-app: 
  image: jboss/keycloak-mysql
  environment:
   - MYSQL_PORT_3306_TCP_PORT=3306
   - MYSQL_DATABASE=keycloak
   - MYSQL_PORT_3306_TCP_ADDR=keycloak-db
   - MYSQL_USER=keycloak
   - MYSQL_PASSWORD=keycloak
   - MYSQL_ROOT_PASSWORD=toor
  links:
    - keycloak-db
  ports:
   - "8080:8080"
openidc-proxy:
  image: alizarion/httpd-proxy-federate
  environment:
  - OIDCProviderMetadataURL=http://localhost:8080/auth/realms/itesoft/.well-known/openid-configuration
  - OIDCClientID=demo-openidc-client
  - OIDCClientSecret=9a56d22b-d725-4c63-b38d-a4b71ecc6fb5
  - OIDCRedirectURI=http://localhost/app1/redirect_uri
  - SAMLMetadataURL=http://localhost:8080/auth/realms/itesoft/protocol/saml/descriptor
  - SAMLClientID=demo-saml-client
  - SAMLEntityID=http://localhost:8080/auth/realms/itesoft
  - http_proxy=${http_proxy}
  - https_proxy=${https_proxy}
  - no_proxy=${no_proxy}
  ports:
   - "80:80"
  links:
   - keycloak-app:localhost
   - app1
   - app2

   
