app1: 
  image: alizarion/openidc-php-demo
  ports:
   - "81:80"
openidc-proxy:
  image: alizarion/openidc-proxy
  environment:
  - OIDCProviderMetadataURL=http://keycloak.crossview.io/auth/realms/${OIDRealm}/.well-known/openid-configuration
  - OIDCClientID=${OIDCClientID}
  - OIDCClientSecret=${OIDCClientSecret}
  - OIDCRedirectURI=http://localhost/app1/redirect_uri
  - http_proxy=${http_proxy}
  - https_proxy=${https_proxy}
  - no_proxy=${no_proxy}
  ports:
   - "80:80"
  links:
   - app1

   
